version: '3'

services:
  database:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: aaraya0
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  front:
    build: ./frontend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
  back:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "80:80"
