apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: backend
          image: gcr.io/${GCP_PROJECT_ID}/ingsw3-final-back:latest
          ports:
            - containerPort: 8080
        - name: frontend
          image: gcr.io/${GCP_PROJECT_ID}/ingsw3-final-front:latest
          ports:
            - containerPort: 3000
        - name: database
          image: gcr.io/${GCP_PROJECT_ID}/ingsw3-final-database:latest
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
