name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Install Dependencies
      run: go mod download

    - name: Run Unit Tests
      working-directory: backend
      run: go test ./...

  docker-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t aaraya0/ingsw3-final-back:latest -f backend/Dockerfile .
        docker push aaraya0/ingsw3-final-back:latest

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t aaraya0/ingsw3-final-front:latest -f frontend/Dockerfile .
        docker push aaraya0/ingsw3-final-front:latest

    - name: Build and Push Database Docker Image
      run: |
        docker build -t aaraya0/ingsw3-final-database:latest -f db/Dockerfile .
        docker push aaraya0/ingsw3-final-database:latest
#    - name: Build and Push Docker Images
#      run: docker-compose build && docker-compose push

