name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and run 
      run: |
         docker compose up -d
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Install Dependencies
      run: go mod download

    - name: Run Unit Tests
      working-directory: backend
      run: go test ./...

  docker-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Tag and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-back:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-front:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-database:latest ./db
          
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-back:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-front:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ingsw3-final-database:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '349.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Configure Docker
        uses: actions/setup-docker@v2
      
      - name: Build and push Docker images to Google Container Registry
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-back:latest ./backend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-front:latest ./frontend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-database:latest ./db
          
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-back:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-front:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ingsw3-final-database:latest
       
